### ISSUE TITLE
Add me as a contributor?

### ISSUE THREAD

**Issue by seanjohnson08** [Jaxboards/Jaxboards#14]
Github won't let me make a fork of your fork, since I'm the owner of the original repo.

I want to help you bring this bad boy back to life. :)

I haven't kept up with modern PHP standards, but I can really add some power behind the JS cleanup initiative.

**Comment by wtl420** [comment]
Huh, that's kinda weird since the repo was renamed. I don't think it'd be a good idea to merge my changes into your repo either since I kinda broke compatibility with it using [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to remove flash files and mp3s from it to shrink down the cloning size LOL.

Of course I'll add you, no problem.

I haven't given much thought to reorganizing the JavaScript yet, though I was thinking of doing shifting it over to TypeScript.
